# 1. 파이썬 3.9 버전이 깔린 가벼운 리눅스를 기본 바탕으로 사용합니다.
FROM python:3.9-slim

# 2. 컨테이너 내부의 작업 디렉토리를 /app으로 설정합니다.
WORKDIR /app

# 3. 내 컴퓨터의 재료 목록을 컨테이너 안으로 복사합니다.
COPY requirements.txt .

# 4. 필요한 라이브러리들을 설치합니다.
RUN pip install --no-cache-dir -r requirements.txt

# 5. 내가 짠 파이썬 코드를 컨테이너 안으로 복사합니다.
COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
